### ISSUE TITLE
Typo in Shadow DOM 201 tutorial's CSS variables code snippet

### ISSUE THREAD

**Issue by kunalkundaje** [html5rocks/www.html5rocks.com#1295]
The first code snippet in the "Using CSS Variables" section has a typo and is missing the var keyword. This seems to be affecting only the English version; the other localized versions look correct.

Currently:
```css
button {
  color: --button-text-color, pink); /* default color will be pink */
  font-family: var(--button-font);
}
```

Should be:
```css
button {
  color: var(--button-text-color, pink); /* default color will be pink */
  font-family: var(--button-font);
}
```
